apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-deployment
  labels:
    app: springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot-container
        image: debago/spring-boot-gradle:#{Build.BuildId}#
        ports:
        - containerPort: 33333
